### ISSUE TITLE
error on install jaspResults

### ISSUE THREAD

**Issue by k-motwani** [jasp-stats/jaspColumnEncoder#1]
Hi, it looks like this cpp module is required for installing jaspResults in R - 
Would it be possible to convert jaspColumnEncoder into an R package so that it can be installed as a jasp submodule/dependency for jaspResults? 

This is the error I'm receiving:

```
* installing *source* package ‘jaspResults’ ...
** using staged installation
** libs
...
columnencoder.cpp:2:10: fatal error: jaspColumnEncoder/columnencoder.cpp: No such file or directory
    2 | #include "jaspColumnEncoder/columnencoder.cpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [lib/R/etc/Makeconf:177: columnencoder.o] Error 1
ERROR: compilation failed for package ‘jaspResults’

```

Thanks!

**Comment by boutinb** [comment]
Hi @k-motwani
I know that this problem occurs when building jasp, if the submodules are not correctly installed (git submodule init, git submodule update --remote). But I'm not so sure how to do that when installing jaspResult in R. Maybe @JorisGoosen or @vandenman know what is the problem.

**Comment by vandenman** [comment]
@k-motwani To install jaspResults you can do in a terminal
```
git clone --recurse-submodules https://github.com/jasp-stats/jaspResults.git
```
followed by
```r
install.packages(<local path to jaspResults clone>, type = "source", repos = NULL)
```
I agree that this is less practical than doing `remotes::install_github("jasp-stats/jaspResults")` (or the same with `renv`/ `pak`).

@JorisGoosen Turning jaspColumnEncoder into an R package would be a straightforward way to solve this, but it does add some unnecessary junk (namespace file, R file, DESCRIPTION, etc.). We could also fix this with a configure script that downloads jaspColumnEncoder if missing (like v8 does). That would be slightly cleaner/ make us less dependant on R packages.

**Comment by JorisGoosen** [comment]
> I agree that this is less practical than doing `remotes::install_github("jasp-stats/jaspResults")` (or the same with `renv`/ `pak`).

Aah yeah, so I wasn't aware that `install_github` wouldn't work with that... Maybe we could send a patch to them to also include submodules? 

> @JorisGoosen Turning jaspColumnEncoder into an R package would be a straightforward way to solve this, but it does add some unnecessary junk (namespace file, R file, DESCRIPTION, etc.). 

Quite a bit of junk right? And also, it really isn't an R package... As in, it really is only cpp for jasp(Results).

>We could also fix this with a configure script that downloads jaspColumnEncoder if missing (like v8 does). That would be slightly cleaner/ make us less dependant on R packages.

This might be better, perhaps we could do `git submodule init` during configure? Or something like that. Otherwise a wget to the repo could also be fine (if not from a git checkout).

**Comment by vandenman** [comment]
> Maybe we could send a patch to them to also include submodules?

The issue is unfortunately a bit more complex because the GitHub API does not make it possible to download a repository AND all its submodules. So you either need to parse `.gitmodules` and download them all recursively or download a repo using `git clone --recurse-submodules`. The former is a bit complex and the latter introduces a system dependency on git. Also, these changes need to be added separately to `remotes`, `renv`, and `pak`.

> This might be better, perhaps we could do git submodule init during configure? Or something like that. Otherwise a wget to the repo could also be fine (if not from a git checkout).

`V8` uses curl. I'm not sure which is more often available on macOS and windows but could try that. We could also do it using R and `utils::download.file` I guess.
